# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#DO NOT USE TABS IN THIS FILE! Use spaces instead :)

gems:
  - jekyll-mentions
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap

# defaults to Github, which is what I want
#jekyll-mentions:
#  base_url: https://twitter.com

# Site settings
title: Alexander Meuer
email: alexmeuer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is where I talk about programming and projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://AlexMeuer.github.io" # the base hostname & protocol for your site
github_username:  AlexMeuer
linkedin_username: AlexMeuer
discord_name: Doraleous
discord_invite_link: https://discord.gg/88n2Xsk
timezone: Europe/Dublin

# Build settings
markdown: kramdown

# Include _pages folder when building site
include: [_pages]
